Explicitly set code sign identity
Without this, builds archived in Xcode are for some reason not signed,
and the builds generated by CI do not have the hardened runtime enabled,
despite the config added in ae824cd.

For some reason, after making this change the CI build started failing,
with `xcodebuild -exportArchive` giving this error:

> error: exportArchive: "MacDown.app" requires a provisioning profile.
>
> Error Domain=IDEProvisioningErrorDomain Code=9 ""MacDown.app" requires a provisioning profile." UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription="MacDown.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

I have no idea why this started happening, but I made the suggested
change to the Export Options plist and it fixed it 🤷.